### ISSUE TITLE
join forces

### ISSUE THREAD

**Issue by vrunoa** [ismaild/whatsapp-desktop#1]
Hey @ismaild wanna join forces ? I was also making a desktop client of whatsapp with grunt & nodewebkit. Check it out <a href="https://github.com/Urucas/desk-whatsapp">https://github.com/Urucas/desk-whatsapp</a>

Regards, bruno

**Comment by ismaild** [comment]
@vrunoa sure. I just re-organized this to be more 'standardized' like other NW projects.

**Comment by vrunoa** [comment]
@ismaild have you checked our repo ? We add a toolbar with the close & minimize button. We also add a function to open the urls in the external browser. There's still a few bugs to fix. If you're interested I could add you as a contributor. What do you think?
